export const enum AdvisorType {
  DEFAULT = "DEFAULT",
  DEBT = "DEBT",
  FRAUD = "FRAUD",
  EMPLOYMENT = "EMPLOYMENT",
  FAMILY = "FAMILY",
  MEDICAL_CONTINGENCY = "MEDICAL_CONTINGENCY",
  INSURANCE = "INSURANCE",
}
